/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type HomePage = {
  _id: string;
  _type: 'homePage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  hero?: {
    tagline?: string;
    title?: string;
    titleEmphasis?: string;
    lead?: string;
    welcomeChip?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: 'image';
    };
    ctas?: Array<{
      label?: string;
      href?: string;
      _key: string;
    }>;
    notes?: Array<{
      label?: string;
      body?: string;
      _key: string;
    }>;
  };
  mission?: {
    eyebrow?: string;
    statement?: string;
    tagline?: string;
  };
  visionStatement?: {
    eyebrow?: string;
    statement?: string;
    tagline?: string;
  };
  programs?: {
    eyebrow?: string;
    title?: string;
    items?: Array<{
      title?: string;
      slug?: Slug;
      summary?: string;
      glyph?: string;
      icon?: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: 'image';
      };
      tone?:
        | 'green-500'
        | 'green-600'
        | 'green-700'
        | 'saffron-400'
        | 'saffron-500'
        | 'red-500'
        | 'earth-700';
      _key: string;
    }>;
  };
  values?: {
    eyebrow?: string;
    title?: string;
    items?: Array<{
      order?: number;
      name?: string;
      description?: string;
      image?: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: 'image';
      };
      _key: string;
    }>;
  };
  originStory?: {
    eyebrow?: string;
    title?: string;
    paragraphs?: Array<string>;
    readMoreLabel?: string;
    href?: string;
    timeline?: Array<{
      date?: string;
      body?: string;
      _key: string;
    }>;
  };
  events?: {
    eyebrow?: string;
    title?: string;
    description?: string;
    allEventsLabel?: string;
    href?: string;
    flyers?: Array<{
      image?: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: 'image';
      };
      href?: string;
      _key: string;
    }>;
  };
  knowYourRights?: {
    eyebrow?: string;
    title?: string;
    description?: string;
    videos?: Array<{
      title?: string;
      url?: string;
      _key: string;
    }>;
  };
  vision?: {
    eyebrow?: string;
    title?: string;
    description?: string;
    ctaLabel?: string;
    href?: string;
    items?: Array<string>;
  };
  membership?: {
    eyebrow?: string;
    title?: string;
    description?: string;
    href?: string;
  };
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | HomePage
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../apps/web/lib/sanity/queries.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_type == "homePage" && _id == "homePage"][0]{    hero{      tagline,      title,      titleEmphasis,      lead,      welcomeChip,      ctas[]{label, href},      image{        alt,        "url": asset->url,        "width": asset->metadata.dimensions.width,        "height": asset->metadata.dimensions.height      }    },    mission{eyebrow, statement, tagline},    visionStatement{eyebrow, statement, tagline},    // Only the section heading. The program cards themselves still come from    // the repo — the detail pages need fields the CMS has no home for yet.    programs{eyebrow, title},    values{      eyebrow,      title,      // Value images exist in the schema but the UI does not render them,      // so they are deliberately not fetched.      items[]{order, name, description}    },    events{      eyebrow,      title,      description,      allEventsLabel,      href,      flyers[]{        href,        image{          alt,          "url": asset->url,          "width": asset->metadata.dimensions.width,          "height": asset->metadata.dimensions.height        }      }    },    knowYourRights{      eyebrow,      title,      description,      videos[]{title, url}    },    // The roadmap strip lower down the page — NOT the formal vision statement,    // which lives in `visionStatement` above.    vision{eyebrow, title, description, ctaLabel, href, items},    membership{eyebrow, title, description, href}  }
export type HOME_PAGE_QUERY_RESULT = {
  hero: {
    tagline: string | null;
    title: string | null;
    titleEmphasis: string | null;
    lead: string | null;
    welcomeChip: string | null;
    ctas: Array<{
      label: string | null;
      href: string | null;
    }> | null;
    image: {
      alt: string | null;
      url: string | null;
      width: number | null;
      height: number | null;
    } | null;
  } | null;
  mission: {
    eyebrow: string | null;
    statement: string | null;
    tagline: string | null;
  } | null;
  visionStatement: {
    eyebrow: string | null;
    statement: string | null;
    tagline: string | null;
  } | null;
  programs: {
    eyebrow: string | null;
    title: string | null;
  } | null;
  values: {
    eyebrow: string | null;
    title: string | null;
    items: Array<{
      order: number | null;
      name: string | null;
      description: string | null;
    }> | null;
  } | null;
  events: {
    eyebrow: string | null;
    title: string | null;
    description: string | null;
    allEventsLabel: string | null;
    href: string | null;
    flyers: Array<{
      href: string | null;
      image: {
        alt: string | null;
        url: string | null;
        width: number | null;
        height: number | null;
      } | null;
    }> | null;
  } | null;
  knowYourRights: {
    eyebrow: string | null;
    title: string | null;
    description: string | null;
    videos: Array<{
      title: string | null;
      url: string | null;
    }> | null;
  } | null;
  vision: {
    eyebrow: string | null;
    title: string | null;
    description: string | null;
    ctaLabel: string | null;
    href: string | null;
    items: Array<string> | null;
  } | null;
  membership: {
    eyebrow: string | null;
    title: string | null;
    description: string | null;
    href: string | null;
  } | null;
} | null;
